# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e88bd3f902cdf52114598f972ffebe38d4785612a55f2ae0403aa7fad2f75f1f8d55e2fcbdf10e5c9fd57cf18d20b4a4b48a33747130652cc32cc33df504aaf

test:
  secret_key_base: 195ab13afc8f58bd4dc1324695101304d3b8c906e95c3e7c2b8582f56d6bd37bcb28a6a04a8e69bde3121564ad5895c3ad84c87db39c20cbc7865557c444cf85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
